"""Modified  Migration

Revision ID: 6d2c73e2a45f
Revises: d4f74a0dc255
Create Date: 2024-12-08 13:31:12.712927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2c73e2a45f'
down_revision: Union[str, None] = 'd4f74a0dc255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_driver_trip_report', 'delay_reports', ['driver_id', 'trip_id'])
    op.drop_index('ix_driver_locations_driver_id', table_name='driver_locations')
    op.create_index(op.f('ix_driver_locations_driver_id'), 'driver_locations', ['driver_id'], unique=True)
    op.create_unique_constraint('unique_trip_sequence', 'intermediate_destinations', ['trip_id', 'sequence'])
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_constraint('unique_trip_sequence', 'intermediate_destinations', type_='unique')
    op.drop_index(op.f('ix_driver_locations_driver_id'), table_name='driver_locations')
    op.create_index('ix_driver_locations_driver_id', 'driver_locations', ['driver_id'], unique=False)
    op.drop_constraint('unique_driver_trip_report', 'delay_reports', type_='unique')
    # ### end Alembic commands ###
